### ISSUE TITLE
Google trends throwing 429

### ISSUE THREAD

**Issue by ratcliffej** [dashee87/cryptory#3]
I'm sorry to report the Google Trends function isn't working. 

It looks like Google have got fed up with PyTrends - it keeps returning an error 429 (too many requests) even with a small request payload. :(

**Comment by ratcliffej** [comment]
It appears to be happening to multiple users, starting today - see link: https://github.com/GeneralMills/pytrends/issues/243

**Comment by dashee87** [comment]
Thanks for linking to the issue on the Pytrends repo! I'll check it regularly and update the code if necessary.

**Comment by ratcliffej** [comment]
Good news! Its been fixed! Run:
pip install --upgrade git+https://github.com/GeneralMills/pytrends
For the latest version.
