### ISSUE TITLE
Coin Market Cap throwing 404

### ISSUE THREAD

**Issue by ghost** [dashee87/cryptory#7]
I believe coin market cap changed how URL params are parsed. Current code base is not working.

line 129 in cryptory.py:
`         output = pd.read_html("https://coinmarketcap.com/currencies/{}/historical-data/?start={}&end={}".format(
                coin, self.from_date.replace("-", ""), self.to_date.replace("-", "")))[0]`

Error

> site-packages/pandas/compat/__init__.py", line 404, in raise_with_traceback
    raise exc.with_traceback(traceback)
urllib.error.HTTPError: HTTP Error 404: NOT FOUND

**Comment by tmlee** [comment]
You might want to consider our open public API at https://www.coingecko.com/api

Happy to answer any questions and concerns you may have!

**Comment by dashee87** [comment]
Hi @tiedtoastar! Not sure if there was a temporary issue with coinmarketcap, but everything looks okay to me. This code runs just fine.

```
from cryptory import Cryptory
my_cryptory = Cryptory(from_date = "2017-01-01", to_date="2018-01-01")
my_cryptory.extract_coinmarketcap("bitcoin")
```

Are you using the latest version of Cryptory? If the problem persists, provide more of your code to let me see what's going on.

**Comment by ghost** [comment]
Sorry, decided to use the cyrptocompare api instead. 
https://github.com/tiedtoastar/monero-etl/blob/master/targets/currencyconversion.py
